server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/theatredb
    username: root
    password: Mysterio61(
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: THEATRE-SERVICE

management:
  tracing:
    sampling:
      probability: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}